### ISSUE TITLE
apply_configuration.py requires git >= 2.28

### ISSUE THREAD

**Issue by RealZiangLiu** [tomsilver/python-starter#7]
The "-b" flag for git init is a feature added after 2.28, which requires extra installation from a PPA on Ubuntu 20.04. Running the [script](https://github.com/tomsilver/python-starter/blob/main/apply_configuration.py#L88) as is causes an error.

Replacing the one-line command with 
`subprocess.run(["git", "init"], check=True, capture_output=True)`
 `subprocess.run(["git", "checkout", "-b", "main"], check=True, capture_output=True)`
seems to work.

**Comment by tomsilver** [comment]
Thanks! Will fix.
